import streamlit as st
from PIL import Image, ImageOps, ImageFilter
import numpy as np
import os
import io
import zipfile
import tempfile
import shutil
import gc
import math # 필터 생성을 위한 수학 모듈

# --- 페이지 설정 ---
st.set_page_config(page_title="CAMPSMAP Pro", page_icon="📸", layout="wide")

st.markdown("""
<style>
    div[data-testid="stImage"] { border-radius: 8px; overflow: hidden; }
    .stButton>button { border-radius: 8px; }
    div.stButton { margin-top: 10px; }
</style>
""", unsafe_allow_html=True)

# --- 필터 설명 ---
FILTER_DESCRIPTIONS = {
    # 베이직
    "Classic": "표준 필름", "Vintage": "따뜻한 빈티지", "Mono": "부드러운 흑백",
    "Kino": "영화 색감", "Kodaclone": "코닥 스타일", "101Clone": "도시적 감성",
    "Art-Club": "몽환적 보라", "Boom-Boom": "강렬한 채도", "Bubblegum": "핑크 파스텔",
    "Cross-Pross": "청록색 틴트", "Eternia": "물 빠진 감성", "Grunge": "거친 락시크",
    "Midas": "황금빛 노을", "Narnia": "겨울 판타지", "Pastel": "순한 봄",
    "Pistachio": "싱그러운 녹색", "Temporum": "세피아 추억", "Uddh": "대지의 색",
    "X-Pro": "강한 대비", "Black_And_White": "강한 흑백", "Bleach": "묵직한 톤",
    # 트렌디 (느좋)
    "Sinsa_Mood": "성수/신사 매트한 톤",
    "Hannam_Chic": "세련된 화이트",
    "Fuji_Air": "후지필름 공기감",
    "Leica_Mono": "깊은 라이카 흑백",
    "Cinestill_Night": "푸른 밤 감성",
    "Portrait_Soft": "인물 피부톤 보정",
}

# -------------------------------------------------------------------
# [Admin] 필터 파일 생성기 (코드로 필터를 만들어서 ZIP으로 줌)
# -------------------------------------------------------------------
def generate_filter_zip():
    zip_buffer = io.BytesIO()
    
    # 커브 함수들
    def curve_s(x, intensity=0.04): return 255 / (1 + math.exp(-intensity * (x - 128)))
    def curve_lift(x, amount=20): return min(255, x + (255-x) * 0.0 + amount * (1 - x/255))
    x_val = list(range(256))
    
    # 필터 레시피 (이름, R, G, B)
    recipes = {
        "Classic": ([curve_s(x, 0.04) for x in x_val], [curve_s(x, 0.04) for x in x_val], [curve_s(x, 0.04) for x in x_val]),
        "Vintage": ([curve_s(x) * 1.1 + 10 for x in x_val], [curve_s(x) * 1.0 + 5 for x in x_val], [curve_s(x) * 0.9 for x in x_val]),
        "Mono": ([curve_s(x, 0.05) for x in x_val], [curve_s(x, 0.05) for x in x_val], [curve_s(x, 0.05) for x in x_val]),
        "Kino": ([x if x < 128 else x * 1.1 for x in x_val], [x for x in x_val], [x * 1.1 if x < 128 else x * 0.9 for x in x_val]),
        "Kodaclone": ([x * 1.05 for x in x_val], [x * 1.02 for x in x_val], [x * 0.95 for x in x_val]),
        "Sinsa_Mood": ([curve_s(x, 0.03) * 1.05 for x in x_val], [curve_s(x, 0.03) * 1.02 for x in x_val], [curve_s(x, 0.03) * 0.9 + 10 for x in x_val]),
        "Hannam_Chic": ([curve_s(x, 0.05) * 0.95 for x in x_val], [curve_s(x, 0.05) for x in x_val], [curve_s(x, 0.05) * 1.1 for x in x_val]),
        "Fuji_Air": ([x * 0.95 for x in x_val], [curve_s(x, 0.04) * 1.05 for x in x_val], [x * 1.1 + 5 for x in x_val]),
        "Leica_Mono": ([255 / (1 + math.exp(-0.06 * (x - 128))) for x in x_val], [255 / (1 + math.exp(-0.06 * (x - 128))) for x in x_val], [255 / (1 + math.exp(-0.06 * (x - 128))) for x in x_val]),
        "Cinestill_Night": ([x * 0.8 if x < 100 else x * 1.2 for x in x_val], [x * 1.05 for x in x_val], [x * 1.2 if x < 100 else x * 0.8 for x in x_val]),
        "Portrait_Soft": ([x + 15 if 50 < x < 200 else x for x in x_val], [x + 5 if 50 < x < 200 else x for x in x_val], [x for x in x_val]),
    }

    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        for name, (r, g, b) in recipes.items():
            r = [min(255, max(0, int(v))) for v in r]
            g = [min(255, max(0, int(v))) for v in g]
            b = [min(255, max(0, int(v))) for v in b]
            
            content = f"Filter Data\nGenerated by CAMPSMAP\nRGB\n{', '.join(map(str, r))}\n{', '.join(map(str, g))}\n{', '.join(map(str, b))}\n"
            zip_file.writestr(f"{name}.flt", content)
            
    return zip_buffer.getvalue()

# --- 필터 로딩 ---
@st.cache_data
def load_filters():
    filters = {}
    current_dir = os.path.dirname(os.path.abspath(__file__))
    possible_paths = [
        os.path.join(current_dir, "Filters"),
        os.path.join(current_dir, "web_app", "Filters"),
        "Filters"
    ]
    
    for filter_dir in possible_paths:
        if not os.path.exists(filter_dir): continue
        try:
            files = [f for f in os.listdir(filter_dir) if f.lower().endswith(('.fit', '.flt'))]
            for fname in files:
                f_name = os.path.splitext(fname)[0]
                if f_name in filters: continue
                with open(os.path.join(filter_dir, fname), 'r', encoding='utf-8', errors='ignore') as f:
                    lines = f.readlines()
                if len(lines) < 7: continue
                lut = []
                for i in range(4, 7):
                    line_data = [int(x) for x in lines[i].replace(',', ' ').split() if x.strip().isdigit()]
                    lut.extend(line_data)
                if len(lut) < 768: lut += [lut[-1]] * (768 - len(lut))
                else: lut = lut[:768]
                filters[f_name] = lut
        except: pass
    return filters

# --- 이미지 처리 ---
def process_base_image(image_input, rotation=0, width=None):
    if isinstance(image_input, bytes):
        img = Image.open(io.BytesIO(image_input))
    else:
        img = image_input

    img = ImageOps.exif_transpose(img) 
    
    if rotation != 0:
        img = img.rotate(rotation, expand=True)
    
    if width:
        w_percent = (width / float(img.size[0]))
        h_size = int((float(img.size[1]) * float(w_percent)))
        img = img.resize((width, h_size), Image.Resampling.LANCZOS)
    
    # 내추럴 필름 룩 설정 (블러 0.1 / 비네팅 0.25 / 노이즈 6)
    base = img.filter(ImageFilter.GaussianBlur(0.1))
    
    w, h = base.size
    x = np.linspace(-1, 1, w).astype(np.float32)
    y = np.linspace(-1, 1, h).astype(np.float32)
    X, Y = np.meshgrid(x, y)
    radius = np.sqrt(X**2 + Y**2)
    mask = 1 - np.clip(radius - 0.5, 0, 1) * 0.25 
    mask = np.repeat(mask[:, :, np.newaxis], 3, axis=2)
    
    arr = np.array(base.convert('RGB'), dtype=np.float32) * mask
    
    noise = np.random.normal(0, 6, (h, w)).astype(np.float32)
    noise = np.repeat(noise[:, :, np.newaxis], 3, axis=2)
    
    final = np.clip(arr + noise, 0, 255).astype(np.uint8)
    
    del arr, noise, X, Y, mask
    return Image.fromarray(final)

def apply_lut(image, lut):
    return image.convert('RGB').point(lut)

# --- 세션 관리 ---
if 'temp_dir' not in st.session_state:
    st.session_state.temp_dir = tempfile.mkdtemp()
if 'saved_files_count' not in st.session_state:
    st.session_state.saved_files_count = 0
if 'current_index' not in st.session_state:
    st.session_state.current_index = 0
if 'rotation_angle' not in st.session_state:
    st.session_state.rotation_angle = 0 
if 'upload_key' not in st.session_state:
    st.session_state.upload_key = 0

# --- 메인 화면 ---
st.title("🎞️ CAMPSMAP Pro")

# --- [사이드바] 필터 관리자 ---
with st.sidebar:
    st.header("🛠️ 관리자 도구")
    st.info("필터 파일이 없다면 아래 버튼을 눌러 다운로드 후, GitHub의 Filters 폴더에 올려주세요.")
    
    # 버튼을 누르면 필터를 즉석에서 만들어서 다운로드 제공
    filters_zip_data = generate_filter_zip()
    st.download_button(
        label="📥 필터 파일 다운로드 (ZIP)",
        data=filters_zip_data,
        file_name="CAMPSMAP_Filters.zip",
        mime="application/zip"
    )

loaded_filters = load_filters()
if not loaded_filters:
    st.warning("⚠️ 현재 적용된 필터가 없습니다. 왼쪽 사이드바에서 필터를 다운받아 GitHub에 업로드해주세요.")
else:
    st.success(f"✅ {len(loaded_filters)}개의 필터가 로드되었습니다.")

uploaded_files = st.file_uploader(
    "사진 업로드 (대량 가능)", 
    type=['jpg', 'jpeg', 'png'], 
    accept_multiple_files=True,
    key=f"uploader_{st.session_state.upload_key}"
)

# 초기화
if not uploaded_files:
    st.session_state.current_index = 0
    st.session_state.saved_files_count = 0
    if os.path.exists(st.session_state.temp_dir):
        shutil.rmtree(st.session_state.temp_dir)
        st.session_state.temp_dir = tempfile.mkdtemp()

if uploaded_files:
    total_files = len(uploaded_files)
    
    # (A) 완료 화면
    if st.session_state.current_index >= total_files:
        st.success(f"🎉 {st.session_state.saved_files_count}장 현상 완료!")
        st.balloons()
        
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
            for root, dirs, files in os.walk(st.session_state.temp_dir):
                for file in files:
                    file_path = os.path.join(root, file)
                    zip_file.write(file_path, arcname=file)
        
        c1, c2 = st.columns(2)
        with c1:
            st.download_button("📦 전체 다운로드", data=zip_buffer.getvalue(), file_name="CAMPSMAP_Result.zip", mime="application/zip", type="primary", use_container_width=True)
        with c2:
            if st.button("🔄 새 작업 시작", use_container_width=True):
                st.session_state.upload_key += 1
                st.session_state.rotation_angle = 0
                st.rerun()

    # (B) 편집 화면
    else:
        gc.collect()
        current_file = uploaded_files[st.session_state.current_index]
        file_bytes = current_file.getvalue()
        
        st.progress((st.session_state.current_index) / total_files)
        
        # 정보 & 회전
        col_info, col_l, col_r = st.columns([4, 1, 1])
        with col_info:
            st.subheader(f"🖼️ [{st.session_state.current_index + 1}/{total_files}] {current_file.name}")
        with col_l:
            if st.button("↺ 왼쪽 회전"):
                st.session_state.rotation_angle = (st.session_state.rotation_angle + 90) % 360
                st.rerun()
        with col_r:
            if st.button("↻ 오른쪽 회전"):
                st.session_state.rotation_angle = (st.session_state.rotation_angle - 90) % 360
                st.rerun()

        # 미리보기
        preview_img = process_base_image(file_bytes, rotation=st.session_state.rotation_angle, width=300)
        
        with st.form(key=f"form_{st.session_state.current_index}"):
            # 로드된 필터가 없으면 버튼 비활성화 방지용 빈 리스트 처리
            if loaded_filters:
                filter_names = sorted(list(loaded_filters.keys()))
            else:
                filter_names = []
                st.error("필터가 없습니다. 사이드바에서 다운로드 후 업로드하세요.")

            cols = st.columns(4)
            selections = {}
            
            for idx, f_name in enumerate(filter_names):
                with cols[idx % 4]:
                    thumb = apply_lut(preview_img, loaded_filters[f_name])
                    st.image(thumb, use_container_width=True)
                    desc = FILTER_DESCRIPTIONS.get(f_name, "")
                    label = f"**{f_name}**"
                    if desc: label += f"\n:gray[{desc}]"
                    selections[f_name] = st.checkbox(label, key=f"chk_{st.session_state.current_index}_{f_name}")
            
            st.divider()
            b1, b2 = st.columns([2, 1])
            with b1:
                submit = st.form_submit_button("✅ 저장 & 다음", type="primary", use_container_width=True)
            with b2:
                skip = st.form_submit_button("⏩ 패스", use_container_width=True)

        if submit:
            selected_filters = [k for k, v in selections.items() if v]
            if not selected_filters:
                st.warning("필터를 선택해주세요.")
            else:
                full_base = process_base_image(file_bytes, rotation=st.session_state.rotation_angle, width=2000)
                fname_no_ext = os.path.splitext(current_file.name)[0]
                
                with st.spinner("저장 중..."):
                    for f_name in selected_filters:
                        final = apply_lut(full_base, loaded_filters[f_name])
                        save_name = f"{fname_no_ext}_{f_name}.jpg"
                        save_path = os.path.join(st.session_state.temp_dir, save_name)
                        final.save(save_path, quality=95, subsampling=0)
                        del final
                        st.session_state.saved_files_count += 1
                
                del full_base
                st.session_state.current_index += 1
                st.rerun()

        if skip:
            st.session_state.current_index += 1
            st.rerun()
